# packages - issues ya vulnerabilities (scan)
# npm-audit: Code scan

name: Dependency Scan

on:
    #workflow_call:
    workflow_dispatch:
      

jobs:
    dependency-check:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout 
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "20"
                cache: "npm"
                cache-dependency-path: |
                  backend/package-lock.json
                  frontend/package-lock.json
            
            - name: Install Backend Dependencies
              working-directory: ./backend
              run: npm install

              # Fails the build if "high" or "critical" vulnerabilities are found
            - name: Run npm Audit for Backend
              working-directory: ./backend
              run: npm audit --audit-level=high

            - name: Install Frontend Dependencies
              working-directory: ./frontend
              run: npm install              

            - name: Run npm Audit for Frontend
              working-directory: ./frontend
              run: npm audit --audit-level=high