# Scan the Dockerfile for issues & CVEs
name: Docker Lint

on: 
    #workflow_call:
    workflow_dispatch:
      

jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            # Lint backend Dockerfile
            - name: Lint Backend Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                  dockerfile: backend/Dockerfile
                  failure-threshold: error   # only fail on errors not warnings

                # Lint frontend Dockerfile
            - name: Lint Frontend Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: frontend/Dockerfile
                failure-threshold: error

            #- name: Validate Docker Compose
            #  run: |
            #    docker compose config --quiet
            #    echo "Docker Compose file is valid"

            #- name: Validate Dockerfile
            #  uses: hadolint/hadolint-action@v3.1.0
            #  with:
            #    dockerfile: "**Dockerfile"
            #    recursive: true

            # Validate docker-compose file
            - name: Validate Docker Compose
              run: docker compose config

            # Validate docker-compose syntax with additional tool
            - name: Install docker-compose-linter
              run: npm install -g dclint

            - name: Lint Docker Compose
              run: dclint docker-compose.yml